services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mentee-management-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=1s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=500ms
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/main/resources:/app/src/main/resources
      - maven-cache:/root/.m2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  maven-cache:

networks:
  default:
    driver: bridge